name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    - name: Docker login
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Version output
      env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "New version: $NEW_VERSION"
    
    # - name: Build docker image
    #   run: |
    #     docker build -t marcomignacco/docker-graphql:2.0.0 .
    #     docker build -t marcomignacco/docker-graphql:latest .

    # - name: Push docker image
    #   run: |
    #     docker push marcomignacco/docker-graphql:2.0.0
    #     docker push marcomignacco/docker-graphql:latest

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
